### ISSUE TITLE
Update Plug with Versioned Doughnut

### ISSUE THREAD

**Issue by mzxyz** [plugblockchain/plug-blockchain#37]
- [x] Refactor Plug to use the new versioned Doughnut enum type
- [x] May require creating and tagging a new release branch for doughnut-rs (includes Cargo.toml version bump)

This should be part of the Plug and CENNZnet 1.0.0-rc2 releases

**Comment by mzxyz** [comment]
Actually this one is more complicated than I though.

https://github.com/plugblockchain/plug-blockchain/blob/0966e9d414e018f7a1ab85b6ed145eb78af590a6/prml/doughnut/src/lib.rs#L40

In doughnut PRML, `Doughnut` type has trait bound `DoughnutApi`, which current `versioned doughnut` has not implemented.

https://github.com/plugblockchain/plug-blockchain/blob/0c183450e980c337821d487b36ab27f754e6f9e2/bin/node/runtime/src/lib.rs#L124
So in the `runtime` implement, there will have problem if we used `versioned doughnut` directly

**Comment by cowboy-bebug** [comment]
We have trouble with the associated types for [DoughnutApi](https://github.com/cennznet/doughnut-rs/blob/master/src/traits/mod.rs#L16-L21) trait because `PlugDoughnut` struct takes `Doughnut: DoughnutApi` as type parameter -> we have to impl DoughnutApi trait for the (versioned enum) Doughnut. We're not sure how to go about defining the associated types for Doughnut (whether to make it generic or remove associated types for fixed types).

A task for this is open here: https://github.com/cennznet/doughnut-rs/issues/38

**Comment by jordy25519** [comment]
I think the `DoughnutApi` trait should be moved so that it is defined here in Plug instead of doughnut-rs. It should only be implemented for `PlugDoughnut` which can then handle the version management internally.
